# Generated by Django 4.1.2 on 2022-10-17 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.BooleanField(default=False),
        ),
    ]
