# Generated by Django 4.1.2 on 2022-10-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_book_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='country',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='store',
            name='open_date',
            field=models.CharField(default='', max_length=100),
        ),
    ]
