# Generated by Django 4.1.2 on 2022-10-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_store_country_store_open_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='coords',
            field=models.CharField(default='0, 0', max_length=50),
        ),
    ]
